ProyectoEcommerce/Models/Empleado.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace ProyectoEcommerce.Models
{
    public class Empleado
    {
        [DisplayName("CÓDIGO")]
        public int codigo { get; set; }
        [DisplayName("NOMBRE DE EMPLEADO")]
        public String nombre { get; set; }
        [DisplayName("FECHA DE NACIMIENTO")]
        public String nacimiento { get; set; }
        [DisplayName("DIRECCIÓN")]
        public String direccion { get; set; }
        [DisplayName("DISTRITO")]
        public String distrito { get; set; }
        [DisplayName("TELÉFONO")]
        public String telefono { get; set; }
        [DisplayName("CARGO")]
        public String cargo { get; set; }
        [DisplayName("FECHA DE CONTRATACIÓN")]
        public String contratacion { get; set; }
        [DisplayName("FOTO")]
        public String foto { get; set; }
    }
}

ProyectoEcommerce/Controllers/EmpleadoController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProyectoEcommerce.Models;

namespace ProyectoEcommerce.Controllers
{
    public class EmpleadoController : Controller
    {

        SqlConnection cn = new SqlConnection(ConfigurationManager.ConnectionStrings["CNX"].ConnectionString);

        // Empleados
        List<Empleado> ListEmpleado()
        {

            List<Empleado> aEmpleados = new List<Empleado>();
            SqlCommand cmd = new SqlCommand("SP_LISTAREMPLEADOS", cn);
            cmd.CommandType = CommandType.StoredProcedure;
            cn.Open();

            try
            {
                SqlDataReader dr = cmd.ExecuteReader();
                while (dr.Read())
                {
                    aEmpleados.Add(new Empleado()
                    {
                        codigo = int.Parse(dr[0].ToString()),
                        nombre = dr[1].ToString(),
                        nacimiento = DateTime.Parse(dr[2].ToString()).ToString("dd/MM/yyyy"),
                        direccion = dr[3].ToString(),
                        distrito = dr[4].ToString(),
                        telefono = dr[5].ToString(),
                        cargo = dr[6].ToString(),
                        contratacion = DateTime.Parse(dr[7].ToString()).ToString("dd/MM/yyyy"),
                        foto = dr[8].ToString()
                    });
                }

                dr.Close();
                cn.Close();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }

            return aEmpleados;
        }

        List<EmpleadoO> ListEmpleadoO()
        {
            List<EmpleadoO> aEmpleados = new List<EmpleadoO>();
            SqlCommand cmd = new SqlCommand("SP_EMPLEADOS", cn);
            cmd.CommandType = CommandType.StoredProcedure;
            cn.Open();
            SqlDataReader dr = cmd.ExecuteReader();

            while (dr.Read())
            {
                aEmpleados.Add(new EmpleadoO()
                {
                    codigo = int.Parse(dr[0].ToString()),
                    nombre = dr[1].ToString(),
                    nacimiento = DateTime.Parse(dr[2].ToString()).ToString("dd/MM/yyyy"),
                    direccion = dr[3].ToString(),
                    distrito = int.Parse(dr[4].ToString()),
                    telefono = dr[5].ToString(),
                    cargo = int.Parse(dr[6].ToString()),
                    contratacion = DateTime.Parse(dr[7].ToString()).ToString("dd/MM/yyyy"),
                    foto = dr[8].ToString()
                });
            }

            dr.Close();
            cn.Close();
            return aEmpleados;
        }

        List<Distrito> ListDistrito()
        {
            List<Distrito> aDistritos = new List<Distrito>();
            SqlCommand cmd = new SqlCommand("SP_LISTARDISTRITOS", cn);
            cmd.CommandType = CommandType.StoredProcedure;
            cn.Open();
            SqlDataReader dr = cmd.ExecuteReader();

            while (dr.Read())
            {
                aDistritos.Add(new Distrito()
                {
                    codigo = int.Parse(dr[0].ToString()),
                    nombre = dr[1].ToString()
                });
            }

            dr.Close();
            cn.Close();
            return aDistritos;
        }

        List<Cargo> ListCargo()
        {
            List<Cargo> aCargos = new List<Cargo>();
            SqlCommand cmd = new SqlCommand("SP_LISTARCARGOS", cn);
            cmd.CommandType = CommandType.StoredProcedure;
            cn.Open();
            SqlDataReader dr = cmd.ExecuteReader();

            while (dr.Read())
            {
                aCargos.Add(new Cargo()
                {
                    codigo = int.Parse(dr[0].ToString()),
                    nombre = dr[1].ToString()
                });
            }

            dr.Close();
            cn.Close();
            return aCargos;
        }

        /*
        public ActionResult Index()
        {
            return View();
        }
        */
        public ActionResult listadoEmpleados()
        {
            return View(ListEmpleado());
        }

        public ActionResult nuevoEmpleado()
        {
            ViewBag.distrito = new SelectList(ListDistrito(), "codigo", "nombre");
            ViewBag.cargo = new SelectList(ListCargo(), "codigo", "nombre");
            ViewBag.codigo = codigoActual();
            return View(new EmpleadoO());
        }
        [HttpPost]
        public ActionResult nuevoEmpleado(EmpleadoO objetoEmpleado)
        {
            if(!ModelState.IsValid)
            {
                return View(objetoEmpleado);
            }

            ViewBag.codigo = codigoActual();

            string fotourl = "";

            if (Request.Files.Count > 0)
            {
                HttpPostedFileBase file = Request.Files[0];

                if (file.ContentLength > 0)
                {
                    string imgname = Path.GetFileName(file.FileName);
                    string extension = Path.GetExtension(imgname);

                    //FileInfo f = new FileInfo(imgname);
                    //string path = Path.GetFullPath(file.FileName);

                    if (extension == ".jpg" || extension == ".png")
                    {
                        //string imgpath = Path.Combine(Server.MapPath("~/fotos_empleados"), imgname);
                        //string fuente = Path.Combine(Directory.GetCurrentDirectory(), imgname);
                        //System.IO.File.Copy(f.FullName, imgpath, true);
                        fotourl = "~/fotos_empleados/" + imgname;
                    }
                }
            }


            cn.Open();
            ViewBag.mensaje = "";
            SqlTransaction tr = cn.BeginTransaction(IsolationLevel.Serializable);
            try
            {
                SqlCommand cmd = new SqlCommand("SP_MANTENIMIENTOEMPLEADO", cn, tr);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@id", objetoEmpleado.codigo);
                cmd.Parameters.AddWithValue("@nom", objetoEmpleado.nombre);
                cmd.Parameters.AddWithValue("@fecha", objetoEmpleado.nacimiento);
                cmd.Parameters.AddWithValue("@dir", objetoEmpleado.direccion);
                cmd.Parameters.AddWithValue("@distrito", objetoEmpleado.distrito);
                cmd.Parameters.AddWithValue("@tel", objetoEmpleado.telefono);
                cmd.Parameters.AddWithValue("@cargo", objetoEmpleado.cargo);
                cmd.Parameters.AddWithValue("@contrat", objetoEmpleado.contratacion);
                cmd.Parameters.AddWithValue("@foto", fotourl);

                int estado = cmd.ExecuteNonQuery();
                tr.Commit();

                ViewBag.mensaje = estado.ToString() + " EMPLEADO REGISTRADO";
            }
            catch (Exception ex)
            {
                ViewBag.mensaje = ex.Message;
                tr.Rollback();
            }

            cn.Close();
            ViewBag.distrito = new SelectList(ListDistrito(), "codigo", "nombre");
            ViewBag.cargo = new SelectList(ListCargo(), "codigo", "nombre");
            return View(objetoEmpleado);

        }

        public ActionResult modificaEmpleado(int id)
        {
            EmpleadoO objetoEmpleado = ListEmpleadoO().Where(c => c.codigo == id).FirstOrDefault();
            ViewBag.distrito = new SelectList(ListDistrito(), "codigo", "nombre", objetoEmpleado.distrito);
            ViewBag.cargo = new SelectList(ListCargo(), "codigo", "nombre", objetoEmpleado.cargo);
            return View(objetoEmpleado);
        }

         [HttpPost]
         public ActionResult modificaEmpleado(EmpleadoO objetoEmpleado)
        {
            if (!ModelState.IsValid)
            {
                return View(objetoEmpleado);
            }

            string fotourl = "";

            if (Request.Files.Count > 0)
            {
                HttpPostedFileBase file = Request.Files[0];

                if (file.ContentLength > 0)
                {
                    string imgname = Path.GetFileName(file.FileName);
                    string extension = Path.GetExtension(imgname);

                    //FileInfo f = new FileInfo(imgname);
                    //string path = Path.GetFullPath(file.FileName);

                    if (extension == ".jpg" || extension == ".png")
                    {
                        //string imgpath = Path.Combine(Server.MapPath("~/fotos_empleados"), imgname);
                        //string fuente = Path.Combine(Directory.GetCurrentDirectory(), imgname);
                        //System.IO.File.Copy(f.FullName, imgpath, true);
                        fotourl = "~/fotos_empleados/" + imgname;
                    }
                }
            }

            cn.Open();
            ViewBag.mensaje = "";
            SqlTransaction tr = cn.BeginTransaction(IsolationLevel.Serializable);
            try
            {
                SqlCommand cmd = new SqlCommand("SP_MANTENIMIENTOEMPLEADO", cn, tr);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@id", objetoEmpleado.codigo);
                cmd.Parameters.AddWithValue("@nom", objetoEmpleado.nombre);
                cmd.Parameters.AddWithValue("@fecha", objetoEmpleado.nacimiento);
                cmd.Parameters.AddWithValue("@dir", objetoEmpleado.direccion);
                cmd.Parameters.AddWithValue("@distrito", objetoEmpleado.distrito);
                cmd.Parameters.AddWithValue("@tel", objetoEmpleado.telefono);
                cmd.Parameters.AddWithValue("@cargo", objetoEmpleado.cargo);

ProyectoEcommerce/Views/Empleado/detalleEmpleado.cshtml
@model ProyectoEcommerce.Models.Empleado

@{
    ViewBag.Title = "LICORERES BALDÍ | DATOS DE EMPLEADO ";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}

<h2 class="text-center pt-4 mb-3">DATOS DE EMPLEADO</h2>

<div>
    <hr />
    <dl class="dl-horizontal form-center">
        <dt>
            @Html.DisplayNameFor(model => model.codigo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.codigo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nacimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nacimiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.direccion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.distrito)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.distrito)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cargo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cargo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.contratacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.contratacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.foto)
        </dt>

        <dd>
            <img class="img-fluid img__listado" src="@Url.Content(Model.foto)" alt="Foto de Empleado" />
        </dd>

    </dl>
</div>
<div class="col-md-12 text-right">
    @Html.ActionLink("VER LISTA", "listadoEmpleados")
</div>

ProyectoEcommerce/Views/Empleado/listadoEmpleados.cshtml
@model IEnumerable<ProyectoEcommerce.Models.Empleado>

@{
    ViewBag.Title = "LICORERES BALDÍ | LISTA DE EMPLEADOS";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}

<h2 class="text-center pt-4">LISTADO GENERAL DE EMPLEADOS</h2>

<p class="text-right">
    @Html.ActionLink("NUEVO EMPLEADO", "nuevoEmpleado", new object { } , new { @class = "btn btn-principal" })
</p>
<table class="table mx-auto justify-content-center text-uppercase">
    <tr>
        <th class="text-center">
            @Html.DisplayNameFor(model => model.codigo)
        </th>
        <th class="text-center">
            @Html.DisplayNameFor(model => model.nombre)
        </th>
        <th class="text-center">
            @Html.DisplayNameFor(model => model.nacimiento)
        </th>
        <th class="text-center">
            @Html.DisplayNameFor(model => model.direccion)
        </th>
        <th class="text-center">
            @Html.DisplayNameFor(model => model.distrito)
        </th>
        <th class="text-center">
            @Html.DisplayNameFor(model => model.telefono)
        </th>
        <th class="text-center">
            @Html.DisplayNameFor(model => model.cargo)
        </th>
        <th class="text-center">
            @Html.DisplayNameFor(model => model.contratacion)
        </th>
        <th class="text-center">
            @Html.DisplayNameFor(model => model.foto)
        </th>
        <th class="text-center">OPCIONES</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td class="align-middle text-center">
            @Html.DisplayFor(modelItem => item.codigo)
        </td>
        <td class="align-middle text-center">
            @Html.DisplayFor(modelItem => item.nombre)
        </td>
        <td class="align-middle text-center">
            @Html.DisplayFor(modelItem => item.nacimiento)
        </td>
        <td class="align-middle text-center">
            @Html.DisplayFor(modelItem => item.direccion)
        </td>
        <td class="align-middle text-center">
            @Html.DisplayFor(modelItem => item.distrito)
        </td>
        <td class="align-middle text-center">
            @Html.DisplayFor(modelItem => item.telefono)
        </td>
        <td class="align-middle text-center">
            @Html.DisplayFor(modelItem => item.cargo)
        </td>
        <td class="align-middle text-center">
            @Html.DisplayFor(modelItem => item.contratacion)
        </td>
        <td class="align-middle text-center">
            <img class="img-fluid img__listado" src="@Url.Content(item.foto)" alt="Foto de Empleado" />
        </td>
        <td class="align-middle text-center">
            <a href="@Url.Action("modificaEmpleado", "Empleado", new { id=item.codigo})" class="btn-mantenimiento">
                <i class="far fa-edit"></i>
            </a>
            <a href="@Url.Action("detalleEmpleado", "Empleado", new { id=item.codigo})" class="btn-mantenimiento">
                <i class="far fa-eye"></i>
            </a>
            <a href="@Url.Action("eliminaEmpleado", "Empleado", new { id=item.codigo})" class="btn-mantenimiento">
                <i class="far fa-trash-alt"></i>
            </a>
        </td>
    </tr>
}

</table>
<hr />

ProyectoEcommerce/Views/Empleado/modificaEmpleado.cshtml
@model ProyectoEcommerce.Models.EmpleadoO

@{
    ViewBag.Title = "LICORERES BALDÍ | MODIFICAR EMPLEADO";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}

<h2 class="text-center pt-4 mb-3">MODIFICA EMPLEADO</h2>

@using (Html.BeginForm("modificaEmpleado", "Empleado", FormMethod.Post, new { enctype = "multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal form-center">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="row mb-3">
            @Html.LabelFor(model => model.codigo, htmlAttributes: new { @class = "control-label col-md-4 mt-1" })
            <div class="col-sm-8">
                @Html.EditorFor(model => model.codigo, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.codigo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row mb-3">
            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-4 mt-1" })
            <div class="col-sm-8">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row mb-3">
            @Html.LabelFor(model => model.nacimiento, htmlAttributes: new { @class = "control-label col-md-4 mt-1" })
            <div class="col-sm-8">
                @Html.EditorFor(model => model.nacimiento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nacimiento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row mb-3">
            @Html.LabelFor(model => model.direccion, htmlAttributes: new { @class = "control-label col-md-4 mt-1" })
            <div class="col-sm-8">
                @Html.EditorFor(model => model.direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.direccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row mb-3">
            @Html.LabelFor(model => model.distrito, htmlAttributes: new { @class = "control-label col-md-4 mt-1" })
            <div class="col-sm-8">
                @Html.DropDownList("distrito", null, new { @class = "form-control" })
            </div>
        </div>

        <div class="row mb-3">
            @Html.LabelFor(model => model.telefono, htmlAttributes: new { @class = "control-label col-md-4 mt-1" })
            <div class="col-sm-8">
                @Html.EditorFor(model => model.telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.telefono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row mb-3">
            @Html.LabelFor(model => model.cargo, htmlAttributes: new { @class = "control-label col-md-4 mt-1" })
            <div class="col-sm-8">
                @Html.DropDownList("cargo", null, new { @class = "form-control" })
            </div>
        </div>

        <div class="row mb-3">
            @Html.LabelFor(model => model.contratacion, htmlAttributes: new { @class = "control-label col-md-4 mt-1" })
            <div class="col-sm-8">
                @Html.EditorFor(model => model.contratacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.contratacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row mb-3">
            @Html.LabelFor(model => model.foto, htmlAttributes: new { @class = "control-label col-md-4 mt-1" })
            <div class="col-sm-8">
                <!--@Html.EditorFor(model => model.foto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.foto, "", new { @class = "text-danger" })-->
                @Html.TextBox("foto", "", new { type = "file", @class = "file-input" })
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-sm-12">
                <input type="submit" value="GUARDAR" class="btn btn-principal" />
            </div>
        </div>
    </div>
}

<div class="col-md-12 text-right">
    @Html.ActionLink("VER LISTA", "listadoEmpleados")
</div>

<script>
    if ('@ViewBag.mensaje' != "") {
        swal('@ViewBag.mensaje', "Presione el botón para cerrar", "success")
    }
</script>

ProyectoEcommerce/Views/Empleado/nuevoEmpleado.cshtml
@model ProyectoEcommerce.Models.EmpleadoO

@{
    ViewBag.Title = "LICORERES BALDÍ | REGISTRO DE EMPLEADO";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}

<h2 class="text-center pt-4 mb-3">NUEVO EMPLEADO</h2>

@using (Html.BeginForm("nuevoEmpleado", "Empleado", FormMethod.Post, new { enctype = "multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal form-center">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="row mb-3">
        @Html.LabelFor(model => model.codigo, htmlAttributes: new { @class = "control-label col-md-4 mt-1" })
        <div class="col-sm-8">
            @Html.EditorFor(model => model.codigo, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", @Value = ViewBag.codigo } })
            @Html.ValidationMessageFor(model => model.codigo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row mb-3">
        @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-4 mt-1" })
        <div class="col-sm-8">
            @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row mb-3">
        @Html.LabelFor(model => model.nacimiento, htmlAttributes: new { @class = "control-label col-md-4 mt-1" })
        <div class="col-sm-8">
            @Html.EditorFor(model => model.nacimiento, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.nacimiento, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row mb-3">
        @Html.LabelFor(model => model.direccion, htmlAttributes: new { @class = "control-label col-md-4 mt-1" })
        <div class="col-sm-8">
            @Html.EditorFor(model => model.direccion, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.direccion, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row mb-3">
        @Html.LabelFor(model => model.distrito, htmlAttributes: new { @class = "control-label col-md-4 mt-2" })
        <div class="col-sm-8">
            @Html.DropDownList("distrito", (SelectList)ViewBag.distrito, "[Seleccione]", new { @class = "form-control" })
        </div>
    </div>

    <div class="row mb-3">
        @Html.LabelFor(model => model.telefono, htmlAttributes: new { @class = "control-label col-md-4 mt-1" })
        <div class="col-sm-8">
            @Html.EditorFor(model => model.telefono, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.telefono, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row mb-3">
        @Html.LabelFor(model => model.cargo, htmlAttributes: new { @class = "control-label col-md-4 mt-1" })
        <div class="col-sm-8">
            @Html.DropDownList("cargo", (SelectList)ViewBag.cargo, "[Seleccione]", new { @class = "form-control" })
        </div>
    </div>

    <div class="row mb-3">
        @Html.LabelFor(model => model.contratacion, htmlAttributes: new { @class = "control-label col-md-4 mt-1" })
        <div class="col-sm-8">
            @Html.EditorFor(model => model.contratacion, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.contratacion, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row mb-3">
        @Html.LabelFor(model => model.foto, htmlAttributes: new { @class = "control-label col-md-4 mt-1" })
        <div class="col-sm-8">
            <!--@Html.EditorFor(model => model.foto, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.foto, "", new { @class = "text-danger" })-->
            @Html.TextBox("foto", "", new { type = "file", @class= "file-input" })
        </div>
    </div>

    <div class="row mb-3">
        <div class="col-sm-12">
            <input type="submit" value="REGISTRAR" class="btn btn-principal" />
        </div>
    </div>
</div>
}

<div class="col-md-12 text-right">
    @Html.ActionLink("VER LISTA", "listadoEmpleados")
</div>

<script>
    if ('@ViewBag.mensaje' != "") {
        swal('@ViewBag.mensaje', "Presione el botón para cerrar", "success")
    }
</script>