ProyectoEcommerce/Controllers/LicoreriaController.cs
using ProyectoEcommerce.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Net.Mail;
using System.Web.Mvc;

namespace ProyectoEcommerce.Controllers
{
    public class LicoreriaController : Controller
    {

        SqlConnection cn = new SqlConnection(ConfigurationManager.ConnectionStrings["CNX"].ConnectionString);

        // Información del cliente

        List<UsuarioO> ListUsuario()
        {
            List<UsuarioO> aUsuarios = new List<UsuarioO>();
            SqlCommand cmd = new SqlCommand("SP_USUARIOS", cn);
            cmd.CommandType = CommandType.StoredProcedure;
            cn.Open();

            try
            {
                SqlDataReader dr = cmd.ExecuteReader();
                while (dr.Read())
                {
                    aUsuarios.Add(new UsuarioO()
                    {
                        codigo = int.Parse(dr[0].ToString()),
                        usuario = dr[1].ToString(),
                        contraseña = dr[2].ToString(),
                        nombre = dr[3].ToString(),
                        email = dr[4].ToString(),
                        dni = dr[5].ToString(),
                        telefono = dr[6].ToString(),
                        token = dr[7].ToString(),
                        rol = int.Parse(dr[8].ToString())
                    });
                }

                dr.Close();
                cn.Close();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }

            return aUsuarios;
        }

        // Productos
        List<Producto> ListProducto()
        {
            List<Producto> aProductos = new List<Producto>();
            SqlCommand cmd = new SqlCommand("SP_LISTARPRODUCTOS", cn);
            cmd.CommandType = CommandType.StoredProcedure;
            cn.Open();

            try
            {
                SqlDataReader dr = cmd.ExecuteReader();
                while (dr.Read())
                {
                    aProductos.Add(new Producto()
                    {
                        codigo = int.Parse(dr[0].ToString()),
                        nombre = dr[1].ToString(),
                        proveedor = dr[2].ToString(),
                        categoria = dr[3].ToString(),
                        canxunidad = dr[4].ToString(),
                        precio = double.Parse(dr[5].ToString()),
                        existencia = int.Parse(dr[6].ToString()),
                        pedido = int.Parse(dr[7].ToString()),
                        foto = dr[8].ToString()
                    });
                }

                dr.Close();
                cn.Close();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }

            return aProductos;
        }

        List<Producto> ListProductoxCatxOrd(int cat, int ord)
        {
            List<Producto> aProductos = new List<Producto>();
            SqlCommand cmd = new SqlCommand("SP_LISTARPRODUCTOSXCATXORD", cn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@cat", cat);
            cmd.Parameters.AddWithValue("@ord", ord);
            cn.Open();

            try
            {
                SqlDataReader dr = cmd.ExecuteReader();
                while (dr.Read())
                {
                    aProductos.Add(new Producto()
                    {
                        codigo = int.Parse(dr[0].ToString()),
                        nombre = dr[1].ToString(),
                        proveedor = dr[2].ToString(),
                        categoria = dr[3].ToString(),
                        canxunidad = dr[4].ToString(),
                        precio = double.Parse(dr[5].ToString()),
                        existencia = int.Parse(dr[6].ToString()),
                        pedido = int.Parse(dr[7].ToString()),
                        foto = dr[8].ToString()
                    });
                }

                dr.Close();
                cn.Close();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }

            return aProductos;
        }

        // Distritos
        List<Distrito> ListDistrito()
        {
            List<Distrito> aDistritos = new List<Distrito>();
            SqlCommand cmd = new SqlCommand("SP_LISTARDISTRITOS", cn);
            cmd.CommandType = CommandType.StoredProcedure;
            cn.Open();
            SqlDataReader dr = cmd.ExecuteReader();

            while (dr.Read())
            {
                aDistritos.Add(new Distrito()
                {
                    codigo = int.Parse(dr[0].ToString()),
                    nombre = dr[1].ToString()
                });
            }

            dr.Close();
            cn.Close();
            return aDistritos;
        }

        // Categorías
        List<Categoria> ListCategoria()
        {
            List<Categoria> aCategorias = new List<Categoria>();
            SqlCommand cmd = new SqlCommand("SP_LISTARCATEGORIAS", cn);
            cmd.CommandType = CommandType.StoredProcedure;
            cn.Open();
            SqlDataReader dr = cmd.ExecuteReader();

            while (dr.Read())
            {
                aCategorias.Add(new Categoria()
                {
                    codigo = int.Parse(dr[0].ToString()),
                    nombre = dr[1].ToString()
                });
            }

            dr.Close();
            cn.Close();
            return aCategorias;
        }

        // Orden
        List<Orden> ListOrden()
        {
            List<Orden> aOrden = new List<Orden>();
            SqlCommand cmd = new SqlCommand("SP_LISTARORDEN", cn);
            cmd.CommandType = CommandType.StoredProcedure;
            cn.Open();
            SqlDataReader dr = cmd.ExecuteReader();

            while (dr.Read())
            {
                aOrden.Add(new Orden()
                {
                    codigo = int.Parse(dr[0].ToString()),
                    nombre = dr[1].ToString()
                });
            }

            dr.Close();
            cn.Close();
            return aOrden;
        }

        // Pedido con datos en String
        List<Pedido> ListPedido()
        {
            List<Pedido> aPedidos = new List<Pedido>();
            SqlCommand cmd = new SqlCommand("SP_LISTARPEDIDOS", cn);
            cmd.CommandType = CommandType.StoredProcedure;
            cn.Open();
            SqlDataReader dr = cmd.ExecuteReader();

            while (dr.Read())
            {
                aPedidos.Add(new Pedido()
                {
                    pedido = int.Parse(dr[0].ToString()),
                    cliente = dr[1].ToString(),
                    fechapedido = dr[2].ToString(),
                    distrito = dr[3].ToString(),
                    direccion = dr[4].ToString(),
                    referencia = dr[5].ToString(),
                    monto = dr[6].ToString()
                });
            }

            dr.Close();
            cn.Close();
            return aPedidos;
        }

        public ActionResult Index()
        {
            return View();
        }

        // Venta de Producto
        /*
        public ActionResult carritoCompras()
        {
            if(Session["carrito"] == null)
            {
                Session["carrito"] = new List<Item>();
            }

            return View(ListProducto());
        }
        */
        public ActionResult carritoCompras(int cat = 0, int ord = 0)
        {
            if (Session["carrito"] == null)
            {
                Session["carrito"] = new List<Item>();
            }

            ViewBag.cat = cat;
            ViewBag.ord = ord;
            ViewBag.categorias = new SelectList(ListCategoria(), "codigo", "nombre");
            ViewBag.orden = new SelectList(ListOrden(), "codigo", "nombre");

            return View(ListProductoxCatxOrd(cat, ord));
        }

        public ActionResult seleccionaProducto(int id)
        {
            Producto objetoProducto = ListProducto().Where(c => c.codigo == id).FirstOrDefault();
            return View(objetoProducto);
        }

        // Enviar el producto seleccionado al carrito
        public ActionResult agregaProducto(int id, int cant = 1)
        {
            var producto = ListProducto().Where(c => c.codigo == id).FirstOrDefault();
            // Enviar información a la clase Item
            Item objetoItem = new Item()
            {
                codigo = producto.codigo,
                descripcion = producto.categoria + " " +producto.nombre + " " + producto.canxunidad,
                precio = producto.precio,
                cantidad = cant,
                foto = producto.foto
            };

            var carrito = (List<Item>)Session["carrito"];
            carrito.Add(objetoItem);
            Session["carrito"] = carrito;

            // Redireccionar
            return RedirectToAction("carritoCompras");
        }

        // Calcular total
        public ActionResult comprarProducto()
        {
            if(Session["carrito"] == null)
            {
                return RedirectToAction("carritoCompras");
            }

            var carrito = (List<Item>) Session["carrito"];
            ViewBag.total = carrito.Sum( sub => sub.subtotal);
            return View(carrito);
        }

        // Eliminar producto de la compra
        public ActionResult eliminaProductoCarrito(int? id = 0)
        {
            if(id == null)
            {
                return RedirectToAction("carritoCompras");
            }

            var carrito = (List<Item>)Session["carrito"];
            var item = carrito.Where(c => c.codigo == id).FirstOrDefault();
            carrito.Remove(item);


            Session["carrito"] = carrito;

ProyectoEcommerce/Views/Licoreria/FinalizarCompra.cshtml
@model ProyectoEcommerce.Models.PedidoO

@{
    ViewBag.Title = "FinalizarCompra";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}

<h2 class="text-center pt-4 mb-3">PEDIDO Nº @ViewBag.pedido — @ViewBag.fecha</h2>

<div class="container">
    <div class="row">
        <div class="col-12">
            <b>DATOS DE CLIENTE</b>
            <hr />
        </div>
        <div class="col-3 text-center text-uppercase">
            <b>DNI:</b> <br />
            @ViewBag.dni
        </div>
        <div class="col-3 text-center text-uppercase">
            <b>NOMBRE COMPLETO:</b> <br />
            @ViewBag.nombre
        </div>
        <div class="col-3 text-center text-uppercase">
            <b>TELÉFONO:</b> <br />
            @ViewBag.telefono
        </div>
        <div class="col-3 text-center text-uppercase">
            <b>EMAIL:</b> <br />
            @ViewBag.email
        </div>
    </div>
</div>
<div class="container pt-4">
    <div class="row">
        <div class="col-12">
            <b>DATOS DE ENTREGA</b>
            <hr />
        </div>
    </div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-row">
                <div class="form-group col-sm-4">
                    @Html.LabelFor(model => model.distrito, htmlAttributes: new { @class = "control-label col-sm-12 mt-2 font-weight-bold" })
                    <div class="col-sm-12">
                        @Html.DropDownList("distrito", (SelectList)ViewBag.distrito, "[Seleccione]", new { @class = "form-control" })
                    </div>
                </div>

                <div class="form-group col-sm-4">
                    @Html.LabelFor(model => model.direccion, htmlAttributes: new { @class = "control-label col-sm-12 mt-2 font-weight-bold" })
                    <div class="col-sm-12">
                        @Html.EditorFor(model => model.direccion, new { htmlAttributes = new { @class = "form-control text-uppercase" } })
                        @Html.ValidationMessageFor(model => model.direccion, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group col-sm-4">
                    @Html.LabelFor(model => model.referencia, htmlAttributes: new { @class = "control-label col-sm-12 mt-2 font-weight-bold" })
                    <div class="col-sm-12">
                        @Html.EditorFor(model => model.referencia, new { htmlAttributes = new { @class = "form-control text-uppercase" } })
                        @Html.ValidationMessageFor(model => model.referencia, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-12 text-center">
                    <input type="submit" value="PAGAR" class="btn btn-principal" />
                </div>
            </div>
        </div>
    }
</div>

ProyectoEcommerce/Views/Licoreria/Index.cshtml
@{
    ViewBag.Title = "LICORERES BALDÍ | INICIO";
}

<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="~/fotos_galeria/galeria1.jpg" class="d-block w-100" alt="foto galeria bar">
        </div>
        <div class="carousel-item">
            <img src="~/fotos_galeria/galeria2.jpg" class="d-block w-100" alt="foto galeria bar">
        </div>
        <div class="carousel-item">
            <img src="~/fotos_galeria/galeria3.jpg" class="d-block w-100" alt="foto galeria bar">
        </div>
        <div class="carousel-item">
            <img src="~/fotos_galeria/galeria4.jpg" class="d-block w-100" alt="foto galeria bar">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="container-fluid">
    <div id="promos">
        <div class="row">
            <div class="col-12 col-md-4 pl-0 pr-3" id="promo-whisky">
                <div class="promos-mensaje mensaje-whisky">
                    <span class="promos-mensaje--whisky">AHORRA HASTA <span class="promo-descuento">30%</span> EN TODO WHISKY</span>
                    <!--<button class="btn btn-light mt-4 btn-promo">VER WHISKIES</button>-->
                    @Html.ActionLink("VER WHISKIES", "listadoWhiskies", "Licoreria", new object { }, new { @class = "btn btn-light mt-4 btn-promo disabled" })
                </div>

            </div>

            <div class="col-12 col-md-4 pl-0 pr-2">
                <div class="promos-mensaje mensaje-cuadricula-cerveza">
                    <span class="promos-mensaje--cerveza"><span class="promo-descuento">20%</span><br /> EN TODO CERVEZA</span>
                    <!--<button class="btn btn-light mt-4 btn-promo">VER CERVEZAS</button>-->
                    @Html.ActionLink("VER CERVEZAS", "listadoCervezas", "Licoreria", new object { }, new { @class = "btn btn-light mt-4 btn-promo disabled" })
                </div>
                <img class="img-fluid pb-2 pt-2 pb-md-2 pt-md-0" src="~/fotos_promociones/promo_cerveza.jpg" alt="" />

                <div class="promos-mensaje mensaje-cuadricula-vino">
                    <span class="promos-mensaje--vino"><span class="promo-descuento">25%</span><br /> EN VINOS SELECTOS</span>
                    <!--<button class="btn btn-light mt-4 btn-promo">VER VINOS</button>-->
                    @Html.ActionLink("VER VINOS", "listadoVinos", "Licoreria", new object { }, new { @class = "btn btn-light mt-4 btn-promo disabled" })
                </div>
                <img class="img-fluid pt-2 pb-2 pt-md-2 pb-md-0" src="~/fotos_promociones/promo_vino.jpg" alt="" />
            </div>
            <div class="col-12 col-md-4 pl-2 pr-0">
                <div class="promos-mensaje mensaje-cuadricula-ron">
                    <span class="promos-mensaje--ron"><span class="promo-descuento">15%</span><br /> EN RON SELECTO</span>
                    <!--<button class="btn btn-light mt-4 btn-promo">VER RONES</button>-->
                    @Html.ActionLink("VER RONES", "listadoRones", "Licoreria", new object { }, new { @class = "btn btn-light mt-4 btn-promo disabled" })
                </div>
                <img class="img-fluid pb-2 pt-2 pb-md-2 pt-md-0" src="~/fotos_promociones/promo_ron.jpg" alt="" />

                <div class="promos-mensaje mensaje-cuadricula-tequila">
                    <span class="promos-mensaje--tequila"><span class="promo-descuento">10%</span><br /> EN TODO TEQUILA</span>
                    <!--<button class="btn btn-light mt-4 btn-promo">VER TEQUILAS</button>-->
                    @Html.ActionLink("VER TEQUILAS", "listadoTequilas", "Licoreria", new object { }, new { @class = "btn btn-light mt-4 btn-promo disabled" })
                </div>
                <img class="img-fluid pt-2" src="~/fotos_promociones/promo_tequila.jpg" alt="" />
            </div>
        </div>
    </div>
</div>

ProyectoEcommerce/Views/Licoreria/PedidoConfirmado.cshtml
@{
    ViewBag.Title = "PedidoConfirmado";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}
<div class="pt-5 pb-5">
    <h1 class="text-center pt-4 mb-3 col-6 mx-auto">Tu pedido ha sido confirmado</h1>
    <div class="text-center col-6 mx-auto">
        <hr />
        <h3>Enviamos los detalles de la compra a tu correo electrónico</h3>
        <h5>Si no puedes verlo, te recomendamos revisar la carpeta de SPAM</h5>
    </div>
    <div class="pt-5 pb-5 text-center">
        <div class="pb-5">
            <h3>Gracias por comprar en Baldí</h3>
        </div>
    </div>
</div>

ProyectoEcommerce/Views/Licoreria/carritoCompras.cshtml
@model IEnumerable<ProyectoEcommerce.Models.Producto>

@{
    ViewBag.Title = "LICORERES BALDÍ | TIENDA";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}

<h2 class="text-center pt-4 mb-5">CARRITO DE COMPRAS</h2>

<div class="container-fluid text-center pt-5">
    @using (Html.BeginForm())
    {
    <div class="d-flex justify-content-around">
        <h4 class="mt-1">CATEGORÍA</h4>
        @Html.DropDownList("cat", (SelectList)ViewBag.categorias, "[Seleccione]", new { @class = "form-control col-2" })
        <h4 class="mt-1">ORDENAR</h4>
        @Html.DropDownList("ord", (SelectList)ViewBag.orden, "[Seleccione]", new { @class = "form-control col-2" })
        <input class="btn btn-principal" type="submit" value="CONSULTAR" />
        @Html.ActionLink("FINALIZAR COMPRA", "comprarProducto", new object { }, new { @class = "btn btn-principal" })
    </div>
    }
</div>


<section id="tienda">
    <div class="row text-center">
        @Html.Partial("_PartialProducto")
    </div>
</section>

ProyectoEcommerce/Views/Licoreria/comprarProducto.cshtml
@model IEnumerable<ProyectoEcommerce.Models.Item>

@{
    ViewBag.Title = "LICORERES BALDÍ | REVISAR PRODUCTOS";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}

<h2 class="text-center pt-4 mb-4">REVISIÓN DEL PEDIDO</h2>

<div class="text-right">
    @Html.ActionLink("SEGUIR COMPRANDO", "carritoCompras", new object { }, new { @class = "btn btn-principal mb-4" })
</div>



<table class="table mx-auto justify-content-center">
    <tr>
        <th class="text-center">
            @Html.DisplayNameFor(model => model.codigo)
        </th>
        <th class="text-center">
            @Html.DisplayNameFor(model => model.descripcion)
        </th>
        <th class="text-center">
            @Html.DisplayNameFor(model => model.precio)
        </th>
        <th class="text-center">
            @Html.DisplayNameFor(model => model.cantidad)
        </th>
        <th class="text-center">
            @Html.DisplayNameFor(model => model.subtotal)
        </th>
        <th class="text-center">
            @Html.DisplayNameFor(model => model.foto)
        </th>
        <th class="text-center"></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td class="align-middle text-center">
                @Html.DisplayFor(modelItem => item.codigo)
            </td>
            <td class="align-middle text-center">
                @Html.DisplayFor(modelItem => item.descripcion)
            </td>
            <td class="align-middle text-center">
                S/. @string.Format("{0:#.00}", Convert.ToDecimal(item.precio))
            </td>
            <td class="align-middle text-center">
                @Html.DisplayFor(modelItem => item.cantidad)
            </td>
            <td class="align-middle text-center">
                S/. @string.Format("{0:#.00}", Convert.ToDecimal(item.subtotal))
            </td>
            <td class="align-middle text-center">
                <img class="img-fluid img__listado" src="@Url.Content(item.foto)" alt="Foto de Producto" />
            </td>
            <td class="align-middle text-center">
                @Html.ActionLink("ELIMINAR", "eliminaProductoCarrito", new { id = item.codigo }, new { @class = "btn btn-principal" })
            </td>
        </tr>
    }
</table>
<hr />
<section id="totales" class="d-flex justify-content-end">
    <p>TOTAL A PAGAR S/. @string.Format("{0:#.00}", Convert.ToDecimal(@ViewBag.total))</p>
</section>

<div class="text-right">
    @Html.ActionLink("CONFIRMAR COMPRA", "FinalizarCompra", new object { }, new { @class = "btn btn-principal mb-4" })
</div>

ProyectoEcommerce/Views/Licoreria/seleccionaProducto.cshtml
@model ProyectoEcommerce.Models.Producto

@{
    ViewBag.Title = "LICORERES BALDÍ | SELECCIONAR PRODUCTO";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}

<section id="seleccion">
    @Html.Partial("_PartialProductoD")
</section>

<section id="info">
    <div class="row mx-auto justify-content-center">
        <div class="col-6">
            <hr />
        </div>
    </div>
    <div class="row mx-auto justify-content-center pt-3 pb-5">
        <div class="col-sm-6 col-md-4">
            <p>
                <span class="font-weight-bold">ENVÍO GRATUITO* POR COMPRAS MAYORES A S/ 199</span>
                <br />
                <span class="envio__distritos">
                    * DISPONIBLE ÚNICAMENTE EN LIMA METROPOLITANA
                </span>
            </p>
            <br />
            <p>
                <span class="font-weight-bold">POLÍTICA DE ENVÍOS</span>
                <br />
                <span class="envio__distritos">
                    AL ORGANIZAR EL TRANSPORTE, ENVÍO, O RECOJO EN TIENDA DE CUALQUIER BEBIDA ALCOHÓLICA, ACCEDE A CONTAR CON UNA IDENTIFICACIÓN VIGENTE PROCEDER CON LA ENTREGA DEL PEDIDO.
                </span>
            </p>
        </div>
        <iframe class="col-sm-4" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3902.775275052931!2d-77.06320808480274!3d-11.990045844113455!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9105ce53c69e3575%3A0x586e76dff7534a44!2sCibertec!5e0!3m2!1ses!2spe!4v1604905994007!5m2!1ses!2spe" width="600" height="200" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
    </div>
</section>